service: lambda-transform

provider:
  name: aws
  runtime: nodejs6.10

functions:
  getCompanies:
    handler: company-service.getCompanies
    events: # endpoint triggering lambda
      - http:
          path: /companies
          method: get

plugins:
  - serverless-webpack

custom:
  webpack: ./webpack.config.js
  webpackIncludeModules: true
